In [1]:
import pandas as pd

In [2]:
data = {
    "student" : ["abhi" , "sachin" , "tanmay" , "wizard" , "gojo"],
    "math" : [95,78,84,89,65],
    "english" : [68,48,98,78,65],
    "sanskrit" : [75,None,90,80,78]
}

In [3]:
data

{'student': ['abhi', 'sachin', 'tanmay', 'wizard', 'gojo'],
 'math': [95, 78, 84, 89, 65],
 'english': [68, 48, 98, 78, 65],
 'sanskrit': [75, None, 90, 80, 78]}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

  student  math  english  sanskrit
0    abhi    95       68      75.0
1  sachin    78       48       NaN
2  tanmay    84       98      90.0
3  wizard    89       78      80.0
4    gojo    65       65      78.0

In [6]:
df.head()

  student  math  english  sanskrit
0    abhi    95       68      75.0
1  sachin    78       48       NaN
2  tanmay    84       98      90.0
3  wizard    89       78      80.0
4    gojo    65       65      78.0

In [11]:
df.isnull().sum()

student     0
math        0
english     0
sanskrit    1
dtype: int64

In [12]:
df.fillna(df.mean(numeric_only=True),inplace=True)

In [13]:
df

  student  math  english  sanskrit
0    abhi    95       68     75.00
1  sachin    78       48     80.75
2  tanmay    84       98     90.00
3  wizard    89       78     80.00
4    gojo    65       65     78.00

In [14]:
df.tail()

  student  math  english  sanskrit
0    abhi    95       68     75.00
1  sachin    78       48     80.75
2  tanmay    84       98     90.00
3  wizard    89       78     80.00
4    gojo    65       65     78.00

In [16]:
df["math"].median()

84.0

In [17]:
df["math"].mode()

0    65
1    78
2    84
3    89
4    95
Name: math, dtype: int64